-- MySQL Script generated by MySQL Workbench
-- Mon Apr 16 12:10:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SPATraductoresDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SPATraductoresDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SPATraductoresDb` DEFAULT CHARACTER SET utf8 ;
USE `SPATraductoresDb` ;

-- -----------------------------------------------------
-- Table `SPATraductoresDb`.`Traductores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPATraductoresDb`.`Traductores` (
  `idTraductores` INT NOT NULL,
  `Email` VARCHAR(90) NULL,
  `User` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  `Name` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `CP` INT(5) NULL,
  `Tlfn` INT(9) NULL,
  PRIMARY KEY (`idTraductores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPATraductoresDb`.`Idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPATraductoresDb`.`Idiomas` (
  `Idioma` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Idioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPATraductoresDb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPATraductoresDb`.`Servicio` (
  `Servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Servicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPATraductoresDb`.`TraductoresQueHablan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPATraductoresDb`.`TraductoresQueHablan` (
  `Idiomas_Idioma` VARCHAR(45) NOT NULL,
  `Traductores_idTraductores` INT NOT NULL,
  PRIMARY KEY (`Idiomas_Idioma`, `Traductores_idTraductores`),
  INDEX `fk_Idiomas_has_Traductores_Traductores1_idx` (`Traductores_idTraductores` ASC),
  INDEX `fk_Idiomas_has_Traductores_Idiomas_idx` (`Idiomas_Idioma` ASC),
  CONSTRAINT `fk_Idiomas_has_Traductores_Idiomas`
    FOREIGN KEY (`Idiomas_Idioma`)
    REFERENCES `SPATraductoresDb`.`Idiomas` (`Idioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Idiomas_has_Traductores_Traductores1`
    FOREIGN KEY (`Traductores_idTraductores`)
    REFERENCES `SPATraductoresDb`.`Traductores` (`idTraductores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPATraductoresDb`.`TraductoresServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPATraductoresDb`.`TraductoresServicio` (
  `Traductores_idTraductores` INT NOT NULL,
  `Servicio_Servicio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Traductores_idTraductores`, `Servicio_Servicio`),
  INDEX `fk_Traductores_has_Servicio_Servicio1_idx` (`Servicio_Servicio` ASC),
  INDEX `fk_Traductores_has_Servicio_Traductores1_idx` (`Traductores_idTraductores` ASC),
  CONSTRAINT `fk_Traductores_has_Servicio_Traductores1`
    FOREIGN KEY (`Traductores_idTraductores`)
    REFERENCES `SPATraductoresDb`.`Traductores` (`idTraductores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Traductores_has_Servicio_Servicio1`
    FOREIGN KEY (`Servicio_Servicio`)
    REFERENCES `SPATraductoresDb`.`Servicio` (`Servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
